module.exports = {
    getDashboardHome(req,res){
     res.render("dashboard/index.ejs",{
        title:"Dashboard",
        page:"dashboard"
     })
    },
    getCollectionsPage(req,res){
        res.render("dashboard/collections.ejs",{
            title:"Collection",
            page:"collections"
         })
    },
    getArtPage(req,res){
        res.render("dashboard/art.ejs",{
            title:"Arts",
            page:"nfts"
         })
    },  
     getNotificationsPage(req,res){
        res.render("dashboard/notifications.ejs",{
            title:"notifications",
            page:"notifications"
         })
    },
    getWalletPage(req,res){
        res.render("dashboard/wallet.ejs",{
            title:"wallet",
            page:"wallet"
         })
    },
}